version: '1.0'
mailer:
    template_dir: './_mailtpl'







mailspool:
    spool_dir: './_mailspool'

    smtp:
        host: 'mail1.leuffen.de'
        port: 25
        username: 'test@leuffen.de'
        sender: 'no-reply@host.xy'
        sender_name: "BrixSender"
        # SMTP password is retrieved vom Keystore <servername>
